name: Deploy to GitHub Pages branch

on:
  push:
    branches:
      - chore/actions

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: node setup
        uses: actions/setup-node@v2
        with:
          node-version: "16"
          cache: "npm"
      - name: installing and building
        run: |
          npm ci
          npm run build
      - name: "deploying docs"
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
          destination_dir: docs
          commit_message: "deploying docs"
      - name: "deploying assets"
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          destination_dir: dist
          commit_message: "deploying assets"
          keep_files: true
      - name: "deploying index.html"
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./index.html
          commit_message: "deploying index.html"
          keep_files: true
