name: Deploy to GitHub Pages branch

on:
  push:
    branches:
      - chore/actions

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: node setup
        uses: actions/setup-node@v2
        with:
          node-version: "16"
          cache: "npm"
      - name: installing and building
        run: |
          npm ci
          npm run build
      - name: prepare artifacts
        run: |
          mkdir public
          mv ./index.html ./public
          mv ./dist ./public
          mv ./docs ./public
      - name: "deploying docs"
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
