name: Deploy to GitHub Pages branch

on:
  push:
    branches:
      - chore/actions

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: node setup
        uses: actions/setup-node@v2
        with:
          node-version: "16"
          cache: "npm"
      - run: |
          npm ci
          npm run build
  deploy:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Deploy docs
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
          commit_message: "deploying docs"
